Constants = {
  ACCESS_TOKEN: 'c8f87fb7dcf0c6b39c7d07b84332377b',
  //Login Actions
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_USER_DETAIL: 'LOGIN_USER_DETAIL',
  REQUEST_FACEBOOK_LOGIN: 'REQUEST_FACEBOOK_LOGIN',
  SET_FACEBOOK_LOGIN: 'SET_FACEBOOK_LOGIN',
  REQUEST_FACEBOOK_LOGIN_FAIL: 'REQUEST_FACEBOOK_LOGIN_FAIL',
  SOCIAL_LOGIN_URL: '/authentication/socialaddlogin',
  GLOBAL_IMAGE_URL: '/authentication/global',
  CHANGE_POPULAR_TOPIC_SELECTED: 'CHANGE_POPULAR_TOPIC_SELECTED',
  GOOGLE_LOGIN_CLIENT_ID_IOS:
    '518885244768-ikg2b91tebusqg6u2e2vldnekfblon0d.apps.googleusercontent.com',
  GOOGLE_WEB_CLIENT_ID:
    '518885244768-5gkg6le9i4l133gs8p4sg9oeokce3ojo.apps.googleusercontent.com',
  USER_NAME_CHANGE: 'USER_NAME_CHANGE',
  REQUEST_USER_SIGNUP: 'REQUEST_USER_SIGNUP',
  SET_USER_SIGNUP: 'SET_USER_SIGNUP',
  REQUEST_USER_SIGNUP_FAIL: 'REQUEST_USER_SIGNUP_FAIL',
  USER_REGISTERATION_URL: '/authentication/addstudent',

  REQUEST_IMAGE_UPLOAD: 'REQUEST_IMAGE_UPLOAD',
  SET_IMAGE_UPLOAD: 'SET_IMAGE_UPLOAD',
  REQUEST_IMAGE_UPLOAD_FAIL:
    'REQUEST_IMAGE_UPLOAD_FAIL' /*
     *Response
     error: 0
  message: "Thank You! Please check your email for username and password."
  results: 1
      */,

  /*email: "k.kaushal50@gmail.com",fullname: "Kaushal",mobile: "9015449250",orgpassword: "Virtual123#",otp: "",password: "a4a79aedce640ce2fbcc32d2e1e5995e"
   */ LOGIN_URL: '/authentication/login',
  HOST_URL: 'https://micro.vstacks.in:3000', //"https://meapisp.madeeasy.in:3000", //
  IMG_URL: 'https://studentportal.madeeasy.in',
  //"https://studentportal.madeeasy.in:3000", //"https://micro.vstacks.in:3000",
  GET_MENU_URL: '/authentication/getmenu',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  //Menu Actions
  DELETE_COMMENT_FORUM: '/forums/deleteComment' /** id: 10394 */,
  DELETE_ANSWER: '/forums/deleteAns' /**id: 11066, userId: 87990 */,
  REQUEST_GLOBAL_URL: 'REQUEST_GLOBAL_URL',
  SET_GLOBAL_URL: 'SET_GLOBAL_URL',
  REQUEST_GLOBAL_URL_FAIL: 'REQUEST_GLOBAL_URL_FAIL',
  GLOBAL_URL: 'GLOBAL_URL',
  REQUEST_MENU: 'REQUEST_MENU',
  RECEIVE_MENU: 'RECEIVE_MENU',
  GET_MENU_FAIL: 'GET_MENU_FAIL',
  SELECTED_MENU: 'SELECTED_MENU',
  INVALIDATE_SELECTED_MENU: 'INVALIDATE_SELECTED_MENU',

  //Request popular topic
  REQUEST_POPULAR_TOPIC: 'REQUEST_POPULAR_TOPIC',
  SET_POPULAR_TOPIC: 'SET_POPULAR_TOPIC',
  REQUEST_FAIL_POPULAR_TOPIC: 'REQUEST_FAIL_POPULAR_TOPIC',
  GET_POPULAR_TOPIC_URL: '/topic/getPopularTopic',

  GET_FORUMS: 'GET_FORUMS',
  GET_FORUMS_SUCCESS: 'GET_FORUMS_SUCCESS',
  GET_FORUMS_FAIL: 'GET_FORUMS_FAIL',
  GET_FORUMS_URL: '/forums', // params {limit: 10, userId: 21, orderby: "id", offset: 0, launchDateCheck: true}

  REQUEST_QUESTION_DETAIL: 'REQUEST_QUESTION_DETAIL',
  SET_QUESTION_DETAIL: 'SET_QUESTION_DETAIL',
  REQUEST_FAIL_QUESTION_DETAIL: 'REQUEST_FAIL_QUESTION_DETAIL',
  GET_QUESTION_DETAIL_URL: '/forums/detail',

  //Trending Topics
  REQUEST_TRENDING_TOPICS: 'REQUEST_TRENDING_TOPICS',
  SET_TRENDING_TOPICS: 'SET_TRENDING_TOPICS',
  REQUEST_TRENDING_TOPICS_FAIL: 'REQUEST_TRENDING_TOPICS_FAIL',
  GET_TRENDING_TOPICS_URL: '/forums/getTrandingTopic', // params {limit: 10, offset: 0}

  // Request Tags
  REQUEST_TAGS: 'REQUEST_TAGS',
  SET_TAGS: 'SET_TAGS',
  REQUEST_FAIL_TAGS: 'REQUEST_FAIL_TAGS',
  GET_TAGS_URL: '/forums/getPostTopic',

  //Like dislike
  REQUEST_POST_LIKE_DISLIKE: 'REQUEST_POST_LIKE_DISLIKE',
  SET_POST_LIKE_DISLIKE: 'SET_POST_LIKE_DISLIKE',
  SET_POST_LIKE_DISLIKE_FAIL: 'SET_POST_LIKE_DISLIKE_FAIL',
  SAVE_LIKE_DISLIKE_URL: '/forums/savePostLike', //{ansId: 40 react: 1/0 userId: 21}

  REQUEST_BOOKMARK: 'REQUEST_BOOKMARK',
  SET_BOOKMARK: 'SET_BOOKMARK',
  SET_BOOKMARK_FAIL: 'SET_BOOKMARK_FAIL',
  SAVE_BOOKMARK_URL: '/forums/bookmark', //{postId: 37 type: "bookmark/unbookmark" userId: 21}
  SET_FREE_DOWNLOADS_BOOKMARKS: 'SET_FREE_DOWNLOADS_BOOKMARKS',
  REQUEST_FREE_DOWNLOADS_BOOKMARKS: 'REQUEST_FREE_DOWNLOADS_BOOKMARKS',
  REQUEST_FAIL_FREE_DOWNLOADS_BOOKMARK: 'REQUEST_FAIL_FREE_DOWNLOADS_BOOKMARK',
  SELECTED_DRAWER_MENU: 'SELECTED_DRAWER_MENU',

  //Solutions
  REGUEST_SOLUTIONS: 'REGUEST_SOLUTIONS',
  SET_SOLUTIONS: 'SET_SOLUTIONS',
  REQUEST_FAIL_SOLUTION: 'REQUEST_FAIL_SOLUTION',
  GET_SOLUTION_URL: '/gatekey/getgatekeycontent', //limit: 20,offset: 0,search: "",userid: 785

  /*
   * BLOGS
   */
  REQUEST_BLOGS: 'REQUEST_BLOGS',
  RECEIVE_BLOGS_SUCCESS: 'RECEIVE_BLOGS_SUCCESS',
  RECEIVE_BLOGS_FAIL: 'RECEIVE_BLOGS_FAIL',
  GET_BLOG_URL: '/blog/getBlogList', //params {userId: 21, status: 1, approve: 1, offset: 0, launchDateCheck: true}

  /*
   * JOBS
   */
  REQUEST_JOBS: 'REQUEST_JOBS',
  RECEIVE_JOBS: 'RECEIVE_JOBS',
  RECEIVE_JOBS_FAIL: 'RECEIVE_JOBS_FAIL',
  GET_POST_TOPIC_URL: '/content/getposttopic', // params: {category: "Job"}
  GET_JOBS_FILTER_URL: '/jobpost/getjobfilterlist', //'/jobpost/getjobfilterlist', //params:{offset: 0, limit: 20, distancestart: "0", distance: "15"}

  /*
   * PG Hostel
   */
  GET_PG_HOSTEL: 'GET_PG_HOSTEL',
  GET_PG_HOSTEL_SUCCESS: 'GET_PG_HOSTEL_SUCCESS',
  GET_PG_HOSTEL_FAIL: 'GET_PG_HOSTEL_FAIL',
  GET_PG_URL: '/pghostelrules/getpgamenitieslist', // params: {id: ""}
  GET_PG_FILTER: '/pghostelrules/getfilterlist', // params:
  /* { BHK: ""
  amenityArry: []
  distance: 15
  distancestart: 0
  endprice: 50000
  lat: ""
  limit: 20
  lng: ""
  offset: 0
  startprice: 0 }  */

  REQUEST_FREE_DOWNLOADS: 'REQUEST_FREE_DOWNLOADS',
  SET_FREE_DOWNLOADS: 'SET_FREE_DOWNLOADS',
  REQUEST_FAIL_FREE_DOWNLOADS: 'REQUEST_FAIL_FREE_DOWNLOADS',
  GET_FREE_DOWNLOAD_URL: '/content/getdownloadcontent', //isbookmark: 0,limit: 20,offset: 0,search: ""

  REQUEST_FREE_DOWNLOADS_SUGGESTIONS: 'REQUEST_FREE_DOWNLOADS_SUGGESTIONS',
  SET_FREE_DOWNLOADS_SUGGESTIONS: 'SET_FREE_DOWNLOADS_SUGGESTIONS',
  REQUEST_FREE_DOWNLOAD_SUGGESTIONS_FAIL:
    'REQUEST_FREE_DOWNLOAD_SUGGESTIONS_FAIL',
  SET_FREE_DOWNLOADS_SEARCHBAR_TEXT: 'SET_FREE_DOWNLOADS_SEARCHBAR_TEXT',
  //Free download content Like dislike and save

  /*REQUEST_FREE_DOWNLOAD_LIKE: "REQUEST_FREE_DOWNLOAD_LIKE",
    SET_FREE_DOWNLOAD_LIKE: "SET_FREE_DOWNLOAD_LIKE",
    REQUEST_FREE_DOWNLOAD_LIKE_FAIL: "REQUEST_FREE_DOWNLOAD_LIKE_FAIL",
  */
  REQUEST_FREE_DOWNLOAD_LIKE_DISLIKE: 'REQUEST_FREE_DOWNLOAD_LIKE_DISLIKE',
  SET_FREE_DOWNLOAD_LIKE_DISLIKE: 'SET_FREE_DOWNLOAD_LIKE_DISLIKE',
  REQUEST_FREE_DOWNLOAD_LIKE_DISLIKE_FAIL:
    'REQUEST_FREE_DOWNLOAD_LIKE_DISLIKE_FAIL',

  REQUEST_FREE_DOWNLOAD_SAVE: 'REQUEST_FREE_DOWNLOAD_SAVE',
  SET_FREE_DOWNLOAD_SAVE: 'SET_FREE_DOWNLOAD_SAVE',
  REQUEST_FREE_DOWNLOAD_SAVE_FAIL: 'REQUEST_FREE_DOWNLOAD_SAVE_FAIL',
  URL_FREE_DOWNLOAD_BOOKMARK: '/content/bookmark',
  URL_FREE_DOWNLOAD_LIKE_DISLIKE: '/content/savepostlike',

  /**/

  GET_MATERIALS: 'GET_MATERIALS',
  GET_MATERIALS_SUCCESS: 'GET_MATERIALS_SUCCESS',
  GET_MATERIALS_FAIL: 'GET_MATERIALS_FAIL',

  GET_KEY_SOLUTION: 'GET_KEY_SOLUTION',
  GET_KEY_SOLUTION_SUCCESS: 'GET_KEY_SOLUTION_SUCCESS',
  GET_KEY_SOLUTION_FAIL: 'GET_KEY_SOLUTION_FAIL',

  REQUEST_TAG_PAGE_DETAIL: 'REQUEST_TAG_PAGE_DETAIL',
  SET_TAG_PAGE_DETAIL: 'SET_TAG_PAGE_DETAIL',
  REQUEST_TAG_PAGE_FAIL: 'REQUEST_TAG_PAGE_FAIL',
  TAG_PAGE_URL: '/topic/detail', //topicId: "56",userId: 785
  TAG_POST_URL: '/forums/', //isbookmark: 0,launchDateCheck: true,limit: 10,offset: 0,orderby: "id",topicId: "56",userId: 785
  REQUEST_TOPIC_FOLLOW: 'REQUEST_TAG_FOLLOW',
  SET_TOPIC_FOLLOW: 'SET_TOPIC_FOLLOW',
  REQUEST_TOPIC_FOLLOW_FAIL: 'REQUEST_TOPIC_FOLLOW_FAIL',
  TOPIC_FOLLOWER_URL:
    '/topic/saveFollower' /**topicId: 56
  userId: 87990
  
  response: {message: "Success", error: 0, results: {id: 3989, topicId: 56, userId: 87990}}
  
  */,
  TOPIC_UNFOLLOWER_API_URL: '/topic/saveunFollower',
  REQUEST_TOPIC_UNFOLLOW: 'REQUEST_TOPIC_UNFOLLOW',
  SET_TOPIC_UNFOLLOW: 'SET_TOPIC_UNFOLLOW',
  REQUEST_TOPIC_UNFOLLOW_FAIL: 'REQUEST_TOPIC_UNFOLLOW_FAIL',
  TOPIC_UNFOLLOWER_URL:
    '/topic/saveunFollower' /**topicId: 56
  userId: 87990 
  
  response: {message: "Success", error: 0, results: 1}
  */,

  REQUEST_PROFILE: 'REQUEST_PROFILE',
  SET_PROFILE: 'SET_PROFILE',
  REFRESH_PROFILE_REDUCER: 'REFRESH_PROFILE_REDUCER',
  REQUEST_PROFILE_FAIL: 'REQUEST_PROFILE_FAIL',
  REQUEST_PROFILE_QUEST: 'REQUEST_PROFILE_QUEST',
  REQUEST_PROFILE_QUEST_FAIL: 'REQUEST_PROFILE_QUEST_FAIL',
  SET_PROFILE_QUEST: 'SET_PROFILE_QUEST',

  REQUEST_FOLLOWERS: 'REQUEST_FOLLOWERS',
  REQUEST_FOLLOWERS_FAIL: 'REQUEST_FOLLOWERS_FAIL',
  SET_FOLLOWERS: 'SET_FOLLOWERS',
  GET_FOLLOWERS_URL: '/topic/getfollower',

  REQUEST_FOLLOW_UNFOLLOW: 'REQUEST_FOLLOW_UNFOLLOW',
  SET_FOLLOW_UNFOLLOW: 'SET_FOLLOW_UNFOLLOW',
  REQUEST_FOLLOW_UNFOLLOW_FAIL: 'REQUEST_FOLLOW_UNFOLLOW_FAIL',

  REQUEST_TOPIC_FOLLOW: 'REQUEST_TOPIC_FOLLOW',
  REQUEST_TOPIC_FOLLOW_FAIL: 'REQUEST_TOPIC_FOLLOW_FAIL',
  SET_FOLLOW_TOPICS: 'SET_FOLLOW_TOPICS',
  GET_FOLLOW_TOPICS_URL: '/topic/followTopic',

  REQUEST_PROFILE_ANSWER: 'REQUEST_PROFILE_ANSWER',
  REQUEST_PROFILE_ANSWER_FAIL: 'REQUEST_PROFILE_ANSWER_FAIL',
  SET_PROFILE_ANSWER: 'SET_PROFILE_ANSWER',
  GET_CITY_LIST: '/session/getcitylist',
  GET_PROFILE_URL: '/faculty/facultyprofile',

  REQUEST_UPDATE_PROFILE: 'REQUEST_UPDATE_PROFILE',
  SET_UPDATE_USER: 'SET_UPDATE_USER',
  REQUEST_UPDATE_USER_FAIL: 'REQUEST_UPDATE_USER_FAIL',
  UPDATE_PROFILE_URL: '/common/updateuser',
  /**dob: "1989-08-25",firstName: "Kaushal",gender: "M",id: 87990,lastName: "yadav",mobile: "9015449250",pAddress1: "Stellar IT Park ",pAddress2: "Noida Sector 62",pCity: "58735",pState: "465",userType: 5
   */ REQUEST_STATE: 'REQUEST_STATE',
  SET_STATE: 'SET_STATE',
  REQUEST_STATE_FAIL: 'REQUEST_STATE_FAIL',
  GET_STATE_URL: '/session/getstatelist',
  REQUEST_STREAM: 'REQUEST_STREAM',
  SET_STREAM: 'SET_STREAM',
  REQUEST_STREAM_FAIL: 'REQUEST_STREAM_FAIL',
  GET_STREAM_URL: '/session/getstreamlist',
  CLEAR_STORE: 'CLEAR_STORE',
  REQUEST_CITY: 'REQUEST_CITY',
  REQUEST_CITY_LIST_FAIL: 'REQUEST_CITY_LIST_FAIL',
  SET_CITY: 'SET_CITY',
  GET_CITY_LIST_URL: '/session/getcitylist', //state :btoa(stateId)
  CHANGE_CITY: 'CHANGE_CITY',
  FIRST_NAME: 'FIRST_NAME',
  LAST_NAME: 'LAST_NAME',
  EMAIL_CHANGED: 'EMAIL_CHANGED',
  DOB_CHANGED: 'DOB_CHANGED',
  GENDER_CHANGED: 'GENDER_CHANGED',
  STREAM_CHANGED: 'STREAM_CHANGED',
  CITY_CHANGED: 'CITY_CHANGED',
  STATE_CHANGED: 'STATE_CHANGED',
  ADDRESS2_CHANGED: 'ADDRESS2_CHANGED',
  ADDRESS1_CHANGED: 'ADDRESS1_CHANGED',
  MOBILE_NO: 'MOBILE_NO',
  IS_PROFILE_UPDATE: 'IS_PROFILE_UPDATE',
  CONFIRM_PASSWORD_CHANGED: 'CONFIRM_PASSWORD_CHANGED',
  NEW_PASSWORD_CHANGED: 'NEW_PASSWORD_CHANGED',
  CURRENT_PASSWORD_CHANGED: 'CURRENT_PASSWORD_CHANGED',
  USER_ID: 'USER_ID',
  EDUCATION: 'EDUCATION',
  REQUEST_UPDATE_PROFILE_ABOUT_US: 'REQUEST_UPDATE_PROFILE_ABOUT_US',
  PROFESSIONAL_SKILLS_CHANGED: 'PROFESSIONAL_SKILLS_CHANGED',
  PREVIOUSLY_WORKING_AT: 'PREVIOUSLY_WORKING_AT',
  CURRENTLY_WORKING_AT: 'CURRENTLY_WORKING_AT',
  REQUEST_IMAGE_UPDATE_STATUS: 'REQUEST_IMAGE_UPDATE_STATUS',
  SET_IMAGE_UPDATE_STATUS: 'SET_IMAGE_UPDATE_STATUS',
  REQUEST_IMAGE_UPDATE_STATUS_FAIL: 'REQUEST_IMAGE_UPDATE_STATUS_FAIL',
  UPDATE_USER_IMAGE_URL: '/common/updateuserimage',
  FROM_ADDRESS_CHANGED: 'FROM_ADDRESS_CHANGED',
  INTRO_CHANGED: 'INTRO_CHANGED',

  //Search filter Feeds
  REQUEST_FEEDS_SUGGESTIONS: 'REQUEST_FEEDS_SUGGESTIONS',
  SET_FEEDS_SUGGESTIONS: 'SET_FEEDS_SUGGESTIONS',
  REQUEST_FEEDS_SUGGESTIONS_FAIL: 'REQUEST_FEEDS_SUGGESTIONS_FAIL',
  SET_FEEDS_SEARCHBAR_TEXT: 'SET_FEEDS_SEARCHBAR_TEXT',
  GET_FEED_SUGGESTION_URL: '/topic/getSearchResults',

  //POST Question
  SET_QUESTION_SEARCHBOX_TEXT: 'SET_QUESTION_SEARCHBOX_TEXT',
  REQUEST_QUESTION_SUGGESTIONS: 'REQUEST_QUESTION_SUGGESTIONS',
  REQUEST_QUESTION_SUGGESTIONS_FAIL: 'REQUEST_QUESTION_SUGGESTIONS_FAIL',
  SET_QUESTION_SUGGESTIONS: 'SET_QUESTION_SUGGESTIONS',
  GET_QUESTION_SUGGESTION_URL: '/forums/searchbytitle',

  //HASH Tag Suggestions

  SET_HASHTAG_SEARCHBOX_TEXT: 'SET_HASHTAG_SEARCHBOX_TEXT',
  REQUEST_HASHTAG_SUGGESTIONS: 'REQUEST_HASHTAG_SUGGESTIONS',
  REQUEST_HASHTAG_SUGGESTIONS_FAIL: 'REQUEST_HASHTAG_SUGGESTIONS_FAIL',
  SET_HASHTAG_SUGGESTIONS: 'SET_HASHTAG_SUGGESTIONS',
  GET_HASHTAG_SUGGESTION_URL: '/topic/getSearchResults',

  SET_TAG_SEARCHBAR_TEXT: 'SET_TAG_SEARCHBAR_TEXT',

  REQUEST_QUESTION_POST: 'REQUEST_QUESTION_POST',
  SET_QUESTION_POST: 'SET_QUESTION_POST',
  REQUEST_POST_QUESTION_FAIL: 'REQUEST_POST_QUESTION_FAIL',
  QUESTION_POST_MEDIA_URL:
    '/file/upload?folder=postAttachment&mediaFor=userPost',

  ///file/upload?folder=${folder}&mediaFor=userProfile

  QUESTION_POST_URL:
    '/forums/add' /** mediaids: [12102]
  postTitle: "hi how I can prepare for PSU?"
  postType: "Question"
  searchtopicInput: [{display: "GATE 2019", value: 28}, {display: "Opportunities after GATE", value: 146}]
  topics: [28, 146]
  OthertopicInput:[{display: "PSU", value: "PSU"}]
  userid: 87990 */,

  REQUEST_QUESTION_EDIT: 'REQUEST_QUESTION_EDIT',
  SET_QUESTION_EDIT: 'SET_QUESTION_EDIT',
  SET_QUESTION_EDIT_FAIL: 'SET_QUESTION_EDIT_FAIL',
  QUESTION_POST_EDIT_URL:
    '/forums/edit' /** OthertopicInput: [{display: "PSU", value: "PSU"}]
  id: 3647
  mediaids: []
  postTitle: "hi how I can prepare for PSU?"
  postType: "Question"
  searchtopicInput: [{display: "GATE 2019", value: 28}]
  0: {display: "GATE 2019", value: 28} */,
  REQUEST_POST_DELETE: 'REQUEST_POST_DELETE',
  SET_POST_DELETE: 'SET_POST_DELETE',
  REQUEST_POST_DELETE_FAIL: 'REQUEST_POST_DELETE_FAIL',
  QUESTION_POST_DELETE_URL: '/forums/deleteForum', //id: 7839 response
  /**error: 0
  message: "success"
  result: [0]
  0: 0
   */
  SELECTED_TAG_OBJECT: 'SELECTED_TAG_OBJECT',
  OTHER_TAG_TEXT: 'OTHER_TAG_TEXT',

  POST_COMMENT_URL:
    '/forums/saveComment' /**comment: "<p>how you can say it is 11 april?</p>↵"
  mediaids: []
  postId: 3675
  userId: 58103 */,
  REQUEST_POST_COMMENT: 'REQUEST_POST_COMMENT',
  SET_POST_COMMENT: 'SET_POST_COMMENT',
  REQUEST_POST_COMMENT_FAIL: 'REQUEST_POST_COMMENT_FAIL',

  REQUEST_SAVE_COMMENT: 'REQUEST_SAVE_COMMENT',
  SET_SAVE_COMMENT: 'SET_SAVE_COMMENT',
  REQUEST_SAVE_COMMENT_FAIL: 'REQUEST_SAVE_COMMENT_FAIL',
  DELETE_COMMENT_LIKE_URL:
    '/forums/deleteCommentLike' /**ansId: 3716
  commentId: 10411
  react: 1
  userId: 58103 */,
  SAVE_COMMENT_LIKE_URL:
    'forums/saveCommentLike' /**commentId: 10371
    react: 1
  userId: 58103 */,

  REQUEST_GET_COMMENTS: 'REQUEST_GET_COMMENTS',
  SET_COMMENTS_LIST: 'SET_COMMENTS_LIST',
  REQUEST_COMMENTS_FAIL: 'REQUEST_COMMENTS_FAIL',
  GET_COMMENTS_URL:
    '/forums/getComments' /**
  limit: 5
  offset: 0
  orderby: "id"
  ordertype: "DESC"
  postId: 3675
  userId: 58103
   */,

  REQUEST_SAVE_ANSWER: 'REQUEST_SAVE_ANSWER',
  SET_SAVE_ANSWER_RESPONSE: 'SET_SAVE_ANSWER_RESPONSE',
  REQUEST_SAVE_ANSWER_FAIL: 'REQUEST_SAVE_ANSWER_FAIL',
  SAVE_ANSWER_URL:
    '/forums/saveAnswer' /**answer: "<p>11 April&nbsp;election date for noida!&nbsp;</p>↵"
  mediaids: []
  postId: 3659
  userId: 21 */,

  USER_LOGOUT: 'USER_LOGOUT',

  /**
   *Test Series
   */
  SET_TEST_SERIES: 'SET_TEST_SERIES',
  REQUEST_TEST_SERIES: 'REQUE_TEST_SERIES',
  REQUEST_TEST_SERIES_FAIL: 'REQUEST_TEST_SERIES_FAIL',

  GET_TEST_SERIES_URL:
    '/test-series/getmainstslist' /*limit: 10
  offset: 0
  orderby: "id"
  streamId: ""
  studentId: 87990
  };*/,

  SET_TEST_SERIES_STREAM: 'SET_TEST_SERIES_STREAM',
  REQUEST_TEST_SERIES_STREAM: 'REQUE_TEST_SERIES_STREAM',
  REQUEST_TEST_SERIES_STREAM_FAIL: 'REQUEST_TEST_SERIES_STREAM_FAIL',
  SELECTED_STREAM_ID: 'SELECTED_STREAM_ID',
  GET_TEST_SERIES_STREAM_URL:
    '/test-series/getteststreams' /*limit: 10
  offset: 0
  orderby: "id"
  streamId: ""
  studentId: 87990*/,

  REQUEST_TEST_SERIES_BY_PAPER_WISE: 'REQUEST_TEST_SERIES_BY_PAPER_WISE',
  SET_TEST_SERIES_BY_PAPER_WISE: 'SET_TEST_SERIES_BY_PAPER_WISE',
  REQUEST_TEST_SERIES_BY_PAPER_WISE_FAIL:
    'REQUEST_TEST_SERIES_BY_PAPER_WISE_FAIL',
  GET_TEST_SERIES_BY_PAPER_WISE_URL: '/test-series/getmainstsPaperWiselist',

  COLLEGE_NAME_CHANGED: 'COLLEGE_NAME_CHANGED',
  MADE_EASY_STUDENT: 'MADE_EASY_STUDENT',
  ADDRESS_CHANGED_TEST_SERIES: 'ADDRESS_CHANGED_TEST_SERIES',
  SESSION_CHANGED_TEST_SERIES: 'SESSION_CHANGED_TEST_SERIES',
  EXAM_CHANGED_TEST_SERIES: 'EXAM_CHANGED_TEST_SERIES',
  COURSE_CHANGED_TEST_SERIES: 'COURSE_CHANGED_TEST_SERIES',

  GET_SESSION_TEST_SERIES_URL: '/session/getsessionlist?cid=', //getsessionlist?cid = 2 // GET request
  GET_EXAM_TYPE_LIST_URL: '/session/getexamtypelist?cid=', //getexamtypelist?cid=2
  GET_COURSE_LIST_URL: '/session/getcourselist?cid=', //getcourselist?cid=

  REQUEST_EXAM_TYPE_LIST: 'REQUEST_EXAM_TYPE_LIST',
  SESSION_CHANGED: 'SESSION_CHANGED',
  GET_COURSE_LIST: 'GET_COURSE_LIST',
  SET_COURSE_LIST: 'SET_COURSE_LIST',
  GET_COURSE_LIST_ERROR: 'GET_COURSE_LIST_ERROR',

  SET_EXAM_TYPE_LIST: 'SET_EXAM_TYPE_LIST',
  GET_EXAM_TYPE_LIST_ERROR: 'GET_EXAM_TYPE_LIST_ERROR',
  GET_COURSE_LIST: 'GET_COURSE_LIST',
  SET_SESSION_LIST: 'SET_SESSION_LIST',
  GET_SESSION_LIST_ERROR: 'GET_SESSION_LIST_ERROR',

  REQUEST_ADD_BILLING_INFO: 'REQUEST_ADD_BILLING_INFO',
  SET_BILLING_INFO: 'SET_BILLING_INFO',
  REQUEST_ADD_BILLING_INFO_FAIL: 'REQUEST_ADD_BILLING_INFO_FAIL',
  TEST_SERIES_ADD_BILLING_INFO_URL: '/test-series/addstudentbillinfo',
  IS_MADE_EASY_STUDENT: 'IS_MADE_EASY_STUDENT',

  REQUEST_STUDENT_INFO_TEST_SERIES: 'REQUEST_STUDENT_INFO_TEST_SERIES',
  SET_STUDENT_INFO_TEST_SERIES: 'SET_STUDENT_INFO_TEST_SERIES',
  REQUEST_STUDENT_INFO_TEST_SERIES_FAIL:
    'REQUEST_STUDENT_INFO_TEST_SERIES_FAIL',
  STUDENT_INFO_TEST_SERIES_URL: '/test-series/getassignpaymetList',

  STUDENT_PURCHAED_TEST_SERIES_LIST: 'test-series/getstudentpurchaselist',
  /**
    address: "Vstacks Infotech Pvt Ltd Office No-11 Ground Floor, STELLAR IT PARK Tower A PLOT NO C/25 SECTOR 62 NOIDA"
  cityId: "58550"
  collegeName: "Jaipuria Institute of Management"
  courseId: "5"
  email: "k.kaushal50@gmail.com"
  examId: "2"
  identityImage: "1557296633099_IMG_7811.JPG"
  ismadeeasy: "yes"
  mobile: "9015449250"
  name: "Kaushal Yadav"
  profileImage: "1557293653005_IMG_7811.JPG"
  sessionId: "3"
  stateId: "465"
  streamId: "5"
  userId: 21
     */

  REQUEST_TEST_PAPER_DATA: 'REQUEST_TEST_PAPER_DATA',
  SET_TEST_PAPER_DATA: 'SET_TEST_PAPER_DATA',
  REQUEST_TEST_PAPER_DATA_FAIL: 'REQUEST_TEST_PAPER_DATA_FAIL',
  GET_TEST_PAPER_DATA_URL: '/test-series/gettestpaperdata' /**id: 20 */,

  /** Group Constants */
  REQUEST_GROUP_LISTING: 'REQUEST_GROUP_LISTING',
  SET_GROUP_LISTING: 'SET_GROUP_LISTING',
  REQUEST_GROUP_LISTING_FAIL: 'REQUEST_GROUP_LISTING_FAIL',
  SUGGESTED_GROUP_LISTING_URL: '/group/sugesstedgroup',
  GROUP_LISTING_URL: '/group/getusergroup',

  /*
   * Group Add filter details URL
   */

  REQUEST_GROUP_SEARCH_LISTING: 'REQUEST_GROUP_SEARCH_LISTING',
  SET_GROUP_SEARCH_LISTING: 'SET_GROUP_SEARCH_LISTING',
  REQUEST_GROUP_SEARCH_LISTING_FAIL: 'REQUEST_GROUP_SEARCH_LISTING_FAIL',
  GROUP_SEARCH_LISTING_URL: '/group/filtergroup',

  //REQUEST_GROUPS: "REQUEST_GROUPS",
  REQUEST_USER_GROUPS: 'REQUEST_USER_GROUPS',

  RECEIVE_USER_GROUP: 'RECEIVE_USER_GROUP',
  USER_GROUP_FAIL: 'USER_GROUP_FAIL',

  REQUEST_SUGGESTED_GROUPS: 'REQUEST_SUGGESTED_GROUPS',
  SET_SUGGESTED_GROUPS: 'SET_SUGGESTED_GROUPS',
  SET_SUGGESTED_GROUP_FAIL: 'SET_SUGGESTED_GROUP_FAIL',

  GET_USERS_GROUP: '/group/getusergroup',
  SUGGESTED_GROUP_URL: '/group/sugesstedgroup', //{userId: 21}

  /** Create a group Constants  */
  REQUEST_CREATE_GROUP: 'REQUEST_CREATE_GROUP',
  SET_CREATE_GROUP: 'SET_CREATE_GROUP',
  REQUEST_CREATE_GROUP_FAIL: 'REQUEST_CREATE_GROUP_FAIL',
  ADD_GROUP_URL: '/group/addgroup', //{aboutGroup: "it is dummy group" action: "Request" createdby: 21 group: "" groupPrivacy: "public" logo: 0 title: "abc"}

  /** Request Group Details  */
  REQUEST_GROUP_DETAILS: 'REQUEST_GROUP_DETAILS',
  SET_GROUP_DETAILS: 'SET_GROUP_DETAILS',
  REQUEST_GROUP_DETAILS_FAIL: 'REQUEST_GROUP_DETAILS_FAIL',
  GET_GROUP_DETAILS_URL: '/group/getgroupdetails', //{group: "MTk%3D", userId: 21}

  /** Request for group feeds */
  REQUEST_GROUP_FEEDS: 'REQUEST_GROUP_FEEDS',
  SET_GROUP_FEEDS: 'SET_GROUP_FEEDS',
  REQUEST_GROUP_FEEDS_FAIL: 'REQUEST_GROUP_FEEDS_FAIL',
  GET_GROUP_FEEDS_URL: '/group/groupfeed', //{group: "MTk%3D", limit: 10, offset: 0, userId: 21}

  //GROUP_FILTER_URL: "/group/filtergroup", //{search: "t" userId: 21}

  /** Request Group Join */
  REQUEST_GROUP_JOIN_LEAVE: 'REQUEST_GROUP_JOIN_LEAVE',
  SET_GROUP_JOIN_LEAVE: 'SET_GROUP_JOIN_LEAVE',
  REQUEST_GROUP_JOIN_LEAVE_FAIL: 'REQUEST_GROUP_JOIN_LEAVE_FAIL',
  GROUP_JOIN_LEAVE_URL: '/group/requestojoin',

  /** group: "MTY3"
  status: "REQUEST_JOIN"
  userId: 87990 */

  // for leave a group
  /*group: "MTY3"
  status: "REQUEST_CANCEL"
  userId: 87990
  */
  REQUEST_GROUP_MEMBERS: 'REQUEST_GROUP_MEMBERS',
  SET_GROUP_MEMBERS: 'SET_GROUP_MEMBERS',
  REQUEST_GROUP_MEMBERS_FAIL: 'REQUEST_GROUP_MEMBERS_FAIL',
  GET_GROUP_MEMBERS_URL:
    '/group/getgroupmemberdetails' /**group: "MTY3"
  userId: 87990 */,

  REQUEST_GROUP_MEMBER_WITH_PASSCODE: 'REQUEST_ADD_GROUP_MEMBER_WITH_PASSCODE',
  SET_GROUP_MEMBER_WITH_PASSCODE: 'SET_GROUP_MEMBER_WITH_PASSCODE',
  REQUEST_GROUP_MEMBER_WITH_PASSCODE_FAIL:
    'REQUEST_GROUP_MEMBER_WITH_PASSCODE_FAIL',
  ADD_MEMBER_WITH_PASSCODE_URL:
    '/group/addGroupUser' /**group: "MzAw"
  userId: 87990 */,

  /** Payment Constants */
  REQUEST_PAYMENT: 'REQUEST_PAYMENT',
  SET_PAYMENT: 'SET_PAYMENT',
  REQUEST_PAYMENT_FAIL: 'REQUEST_PAYMENT_FAIL',
  CREATE_PAYMENT_URL: '/payment/creatPayment',

  ADD_POST_URL:
    '/group/addpost' /**content: "<p><img alt="1557147877472_20190506_183056.png" src="https://meapisp.madeeasy.in:3000/ckeditor/1557722464868_1557147877472_20190506_183056.png" /></p>↵"
  group: "MTY3"
  userId: 87990 */,
  DELETE_FEED_URL: '/group/deletefeed' /**id: 1882
  userId: 87990 */,
  GROUP_COMMENT_LIKE:
    '/group/savecommentlike' /** commentId: 5389
  postId: 3184
  react: 1
  userId: 87990 */,

  GROUP_DELETE_COMMENT_LIKE:
    '/group/deletecommentlike' /**
  commentId: 5333
  postId: 3184
  react: 1
  userId: 87990
   */,
  GROUP_SAVE_COMMENT_URL:
    '/group/savecomment' /**comment: "<p>hello</p>↵"
  postId: 1889
  userId: 87990 
  
  comment: "<p>Hi test</p>↵↵<p><img alt="0f6bcc55-9843-460e-a5cb-b318b9ba6945.jpeg" src="https://meapisp.madeeasy.in:3000/ckeditor/1558431692353_0f6bcc55-9843-460e-a5cb-b318b9ba6945.jpeg" /></p>↵↵<p>&nbsp;</p>↵↵<p>Hello</p>↵↵<p><img alt="Screenshot 2019-05-21 at 10.50.23 AM.png" src="https://meapisp.madeeasy.in:3000/ckeditor/1558431713708_Screenshot_2019-05-21_at_10.50.23_AM.png" /></p>↵"
  postId: 1889
  userId: 19453
  
  
  */,
  GROUP_COMMENT_DELETE_URL: '/group/deletecomment', //id: 3569,

  GET_GROUP_COMMENTS_URL:
    '/group/getcomments' /**limit: 5,
  offset: 0
  orderby: "id"
  ordertype: "DESC"
  postId: 1889
  userId: 87990 */,
  /** Job Detail Constants */
  REQUEST_JOB_DETAIL: 'REQUEST_JOB_DETAIL',
  SET_JOB_DETAIL: 'SET_JOB_DETAIL',
  REQUEST_JOB_DETAIL_FAIL: 'REQUEST_JOB_DETAIL_FAIL',
  JOB_DETAIL_URL: '/jobpost/getjobdetails',

  /** Job Detail Constants */
  REQUEST_JOB_IAM_INTERESTED: 'REQUEST_JOB_IAM_INTERESTED',
  SET_JOB_IAM_INTERESTED: 'SET_JOB_IAM_INTERESTED',
  REQUEST_JOB_IAM_INTERESTED_FAIL: 'REQUEST_JOB_IAM_INTERESTED_FAIL',
  JOB_IAM_INTERESTED_URL: '/content/iaminterest',

  GROUP_ATTACHMENT_URL:
    'https://meapisp.madeeasy.in:3000/file/upload?folder=ckeditor&mediaFor=ckeditor',
  /*
   * JOBS
   */
  REQUEST_JOB_SEARCH: 'REQUEST_JOB_SEARCH',
  SET_JOB_SEARCH: 'SET_JOB_SEARCH',
  REQUEST_JOB_SEARCH_FAIL: 'REQUEST_JOB_SEARCH_FAIL',
  JOB_SEARCH_URL: '/jobpost/getjobfilterlist',

  REQUEST_INVOICE_LIST: 'REQUEST_INVOICE_LIST',
  SET_INVOICE_LIST: 'SET_INVOICE_LIST',
  REQUEST_INVOICE_LIST_FAIL: 'REQUEST_INVOICE_LIST_FAIL',
  INVOICE_LIST_URL: '/test-series/getinvoicelist',

  GENERATE_INVOCIE_LIST_URL: '/test-series/generateinvoice',
  REQUEST_GENERATE_INVOICE_LIST: 'REQUEST_GENERATE_INVOICE_LIST',
  SET_GENERATE_INVOICE_LIST: 'SET_GENERATE_INVOICE_LIST',
  REQUEST_GENERATE_INVOICE_LIST_FAIL: 'REQUEST_GENERATE_INVOICE_LIST_FAIL',

  GENERATE_INVOICE_PDF_URL: '/test-series/generateinvoicepdf',
  REQUEST_INVOICE_PDF: 'REQUEST_INVOICE_PDF',
  SET_INVOICE_PDF: 'SET_INVOICE_PDF',
  REQUEST_INVOICE_PDF_FAIL: 'REQUEST_INVOICE_PDF_FAIL',
  UPLOAD_PROGRESS: 'UPLOAD_PROGRESS',
  USER_FOLLOWER_API:
    '/forums/userFollower' /** f_userid: 58103
  t_userid: 58103 */,
  /* response : result: "sub" for unfollow
   * result:add for follow
   */ TOPIC_FOLLOWER_API:
    '/topic/saveFollower' /**topicId: 56
  userId: 19453 */,
  TOPIC_UNFOLLOWER: '/topic/saveunFollower' /**topicId: 56
  userId: 19453 */,
  GROUP_SAVE_POST_LIKE:
    '/group/savepostlike' /**postId: 1889
  react: 1
  userId: 19453 */,

  /** TEST PAPER REPORT  */
  /* GET_TEST_PAPER_REPORT: "GET_TEST_PAPER_REPORT",
    SET_TEST_PAPER_REPORT: "SET_TEST_PAPER_REPORT",
    FAIL_TEST_PAPER_REPORT: "FAIL_TEST_PAPER_REPORT",
    URL_TEST_PAPER_REPORT: "test-series/getAllReportList",
   */

  TEST_PAPER_REPORT: {
    GET: 'GET_TEST_PAPER_REPORT',
    SET: 'SET_TEST_PAPER_REPORT',
    FAIL: 'FAIL_TEST_PAPER_REPORT',
    URL: 'test-series/getAllReportList',
  },
  REPORT_PACKAGE: {
    GET: 'GET_REPORT_PACKAGE',
    SET: 'SET_REPORT_PACKAGE',
    FAIL: 'FAIL_REPORT_PACKAGE',
    URL: 'test-series/getreportmainstslist',
  },
  REPORT_TEST_TYPE: {
    GET: 'GET_REPORT_TEST_TYPE',
    SET: 'SET_REPORT_TEST_TYPE',
    FAIL: 'FAIL_REPORT_TEST_TYPE',
    URL: 'test-series/gettestpaperdropdownlist',
  },
  REPORT_TEST_TYPE: {
    GET: 'GET_REPORT_TEST_TYPE',
    SET: 'SET_REPORT_TEST_TYPE',
    FAIL: 'FAIL_REPORT_TEST_TYPE',
    URL: 'test-series/gettestpaperdropdownlist',
  },
  REPORT_STUDENT_DETAIL: {
    GET: 'GET_REPORT_STUDENT_DETAIL',
    SET: 'SET_REPORT_STUDENT_DETAIL',
    FAIL: 'FAIL_REPORT_STUDENT_DETAIL',
    URL: 'test-series/getStudentDetailedReport',
  },
  REPORT_QUESTION_WISE: {
    GET: 'GET_REPORT_QUESTION_WISE',
    SET: 'SET_REPORT_QUESTION_WISE',
    FAIL: 'FAIL_REPORT_QUESTION_WISE',
    URL: 'test-series/getstudentreportlist',
  },
  CREATE_GROUP: {
    GET: 'REQUEST_CREATE_GROUP',
    SET: 'SET_CREATE_GROUP_RESPONSE',
    FAIL: 'REQUEST_CREATE_GROUP_FAIL',
    URL: '/group/addgroup',
  },
  STUDENT_UPLOAD_LIST: {
    GET: 'REQUEST_STUDENT_UPLOAD_LIST',
    SET: 'SET_STUDENT_UPLOAD_LIST',
    FAIL: 'REQUEST_STUDENT_UPLOAD_LIST_FAIL',
    URL: '/test-series/getstudentuploadlist',
  },
  FORGOT_PASSWORD: {
    GET: 'REQUEST_FORGOT_PASSWORD',
    SET: 'SET_FORGOT_PASSWORD',
    FAIL: 'REQUEST_FORGOT_PASSWORD_FAIL',
    URL: '/authentication/resetpasswordfront',
  },
  GET_NOTIFICATION: {
    GET: 'REQUEST_NOTIFICATION',
    SET: 'SET_NOTIFICATION',
    FAIL: 'REQUEST_NOTIFICATION_FAIL',
    URL: '/notification/getLatestNtf', // userId:87990
  },

  MORE_TOPIC: {
    GET: 'GET_MORE_TOPIC',
    SET: 'SET_MORE_TOPIC',
    FAIL: 'FAIL_MORE_TOPIC',
    URL: 'topic/getTopic',
  },
  FEEDS: {
    GET: 'GET_FEEDS',
    SET: 'SET_FEEDS',
    FAIL: 'FAIL_FEEDS',
    URL: 'forums/',
    GET_BOOKMARK: 'GET_BOOKMARK',
    SET_BOOKMARK: 'SET_BOOKMARK',
  },
  USER_PROFILE: {
    GET: 'GET_USER_PROFILE',
    SET: 'SET_USER_PROFILE',
    FAIL: 'FAIL_USER_PROFILE',
    URL: '/authentication/userdataforprofile',
  },
  PASSWORD_CHANGE: {
    GET: 'GET',
    SET: 'SET',
    FAIL: 'FAIL',
    URL: '/common/changeuserpassword',
    REQUEST_PASSWORD_CHANGED: 'REQUEST_PASSWORD_CHANGED',
    SET_PASSWORD_CHANGED: 'SET_PASSWORD_CHANGED',
    REQUEST_PASSWORD_CHANGED_FAIL: 'REQUEST_PASSWORD_CHANGED_FAIL',
  },
  HELP_DESK: {
    GET: 'GET',
    SET: 'SET',
    FAIL: 'FAIL',
    URL: '/helpdesk/catdropdownlist',
  },
  HELP_DESK_ADD_TICKET: {
    GET: 'HELP_DESK_ADD_TICKET.GET',
    SET: 'HELP_DESK_ADD_TICKET.SET',
    FAIL: 'HELP_DESK_ADD_TICKET.FAIL',
    URL:
      '/helpdesk/addhelpdeskticket' /**imagearry: []
  ticketdata: {supportType: "3",…}
  createdBy: 58103
  description: "<p><a href="http://www.google.com">http://www.google.com</a>&nbsp;there</p>↵"
  supportType: "3" */,
  },
  HELP_DESK_GET_TICKETS: {
    GET: 'HELP_DESK_GET_TICKETS.GET',
    SET: 'HELP_DESK_GET_TICKETS.SET',
    FAIL: 'HELP_DESK_GET_TICKETS.FAIL',
    URL:
      '/helpdesk/gethelpticketlist' /**limit: 20
  offset: 0
  userId: 58103 */,
  },
  UPDATE_HELP_DESK_TICKET: {
    GET: 'UPDATE_HELP_DESK_TICKET_GET',
    SET: 'UPDATE_HELP_DESK_TICKET_SET',
    FAIL: 'UPDATE_HELP_DESK_TICKET_FAIL',
    URL: '/helpdesk/updatehelpdeskticket',
  },
  ADD_HELP_DESK_TICKET_COMMENT: {
    GET: 'ADD_HELP_DESK_TICKET_COMMENT_GET',
    SET: 'ADD_HELP_DESK_TICKET_COMMENT_SET',
    FAIL: 'ADD_HELP_DESK_TICKET_COMMENT_FAIL',
    URL: '/helpdesk/addhelpcomment',
    CLEAR_STATE: 'CLEAR_STATE',
  },
  DELETE_HELP_DESK_TICKET_COMMENT: {
    GET: 'DELETE_HELP_DESK_TICKET_COMMENT_GET',
    SET: 'DELETE_HELP_DESK_TICKET_COMMENT_SET',
    FAIL: 'DELETE_HELP_DESK_TICKET_COMMENT_FAIL',
    URL: '/helpdesk/deleteusercomment',
  },
};

export default Constants;
